# Generated by Django 5.2.12 on 2026-03-15 02:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Provincia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("codigo", models.CharField(max_length=4, unique=True)),
                ("nombre", models.CharField(max_length=100)),
            ],
            options={
                "verbose_name": "Provincia",
                "verbose_name_plural": "Provincias",
                "ordering": ["codigo"],
            },
        ),
        migrations.CreateModel(
            name="Region",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("codigo", models.CharField(max_length=4, unique=True)),
                ("nombre", models.CharField(max_length=100)),
                (
                    "macrozona",
                    models.CharField(
                        choices=[
                            ("norte_grande", "Norte Grande"),
                            ("norte_chico", "Norte Chico"),
                            ("central", "Central"),
                            ("metropolitana", "Metropolitana"),
                            ("sur", "Sur"),
                            ("austral", "Austral"),
                        ],
                        max_length=50,
                    ),
                ),
            ],
            options={
                "verbose_name": "Región",
                "verbose_name_plural": "Regiones",
                "ordering": ["codigo"],
            },
        ),
        migrations.CreateModel(
            name="Comuna",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cut", models.CharField(max_length=5, unique=True)),
                ("nombre", models.CharField(max_length=100)),
                ("poblacion", models.IntegerField()),
                ("padron_electoral", models.IntegerField()),
                (
                    "ruralidad_pct",
                    models.FloatField(
                        help_text="Porcentaje de población rural (0-100)"
                    ),
                ),
                ("latitud", models.FloatField()),
                ("longitud", models.FloatField()),
                (
                    "geojson",
                    models.JSONField(
                        blank=True, help_text="Geometría de polígono comunal", null=True
                    ),
                ),
                (
                    "provincia",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="comunas",
                        to="comunas.provincia",
                    ),
                ),
            ],
            options={
                "verbose_name": "Comuna",
                "verbose_name_plural": "Comunas",
                "ordering": ["cut"],
            },
        ),
        migrations.AddField(
            model_name="provincia",
            name="region",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="provincias",
                to="comunas.region",
            ),
        ),
    ]
