# Generated by Django 5.2.12 on 2026-03-15 02:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="EjecucionModelo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fecha_inicio", models.DateTimeField(auto_now_add=True)),
                ("fecha_fin", models.DateTimeField(blank=True, null=True)),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("pendiente", "Pendiente"),
                            ("corriendo", "Corriendo"),
                            ("completado", "Completado"),
                            ("error", "Error"),
                        ],
                        default="pendiente",
                        max_length=20,
                    ),
                ),
                ("draws", models.IntegerField(default=300)),
                ("tune", models.IntegerField(default=300)),
                ("chains", models.IntegerField(default=2)),
                ("seed", models.IntegerField(default=81850)),
                ("log", models.TextField(blank=True)),
            ],
            options={
                "verbose_name": "Ejecución del modelo",
                "verbose_name_plural": "Ejecuciones del modelo",
                "ordering": ["-fecha_inicio"],
            },
        ),
        migrations.CreateModel(
            name="ParametroModelo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100)),
                ("media", models.FloatField()),
                ("desviacion", models.FloatField()),
                (
                    "ic_low",
                    models.FloatField(help_text="Intervalo credibilidad 94% inferior"),
                ),
                (
                    "ic_high",
                    models.FloatField(help_text="Intervalo credibilidad 94% superior"),
                ),
                (
                    "r_hat",
                    models.FloatField(
                        help_text="Diagnóstico de convergencia — ideal < 1.01"
                    ),
                ),
                (
                    "ejecucion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="parametros",
                        to="modelo.ejecucionmodelo",
                    ),
                ),
            ],
            options={
                "verbose_name": "Parámetro del modelo",
                "verbose_name_plural": "Parámetros del modelo",
                "ordering": ["ejecucion", "nombre"],
            },
        ),
    ]
