# Generated by Django 5.2.12 on 2026-03-15 02:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("comunas", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Candidato",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100)),
                ("sigla", models.CharField(max_length=10)),
                (
                    "color_hex",
                    models.CharField(
                        help_text="Color para visualización, ej: #E24B4A", max_length=7
                    ),
                ),
                ("descripcion", models.TextField(blank=True)),
                ("activo_segunda_vuelta", models.BooleanField(default=False)),
            ],
            options={
                "verbose_name": "Candidato",
                "verbose_name_plural": "Candidatos",
                "ordering": ["sigla"],
            },
        ),
        migrations.CreateModel(
            name="Eleccion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100)),
                (
                    "vuelta",
                    models.IntegerField(
                        choices=[(1, "Primera vuelta"), (2, "Segunda vuelta")]
                    ),
                ),
                ("fecha", models.DateField()),
                ("descripcion", models.TextField(blank=True)),
            ],
            options={
                "verbose_name": "Elección",
                "verbose_name_plural": "Elecciones",
                "ordering": ["fecha", "vuelta"],
            },
        ),
        migrations.CreateModel(
            name="EntropiaComuna",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "entropia_shannon",
                    models.FloatField(help_text="H = -Σ p_i · log2(p_i)"),
                ),
                (
                    "magnitud_quake",
                    models.FloatField(
                        blank=True,
                        help_text="log10 del cambio absoluto de votos respecto a elección anterior",
                        null=True,
                    ),
                ),
                (
                    "comuna",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="entropias",
                        to="comunas.comuna",
                    ),
                ),
                (
                    "eleccion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="entropias",
                        to="elecciones.eleccion",
                    ),
                ),
            ],
            options={
                "verbose_name": "Entropía comunal",
                "verbose_name_plural": "Entropías comunales",
                "ordering": ["-entropia_shannon"],
                "unique_together": {("comuna", "eleccion")},
            },
        ),
        migrations.CreateModel(
            name="FlujoTransicion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "probabilidad_media",
                    models.FloatField(help_text="Media posterior del modelo bayesiano"),
                ),
                (
                    "probabilidad_ic_low",
                    models.FloatField(
                        help_text="Límite inferior intervalo credibilidad 94%"
                    ),
                ),
                (
                    "probabilidad_ic_high",
                    models.FloatField(
                        help_text="Límite superior intervalo credibilidad 94%"
                    ),
                ),
                (
                    "candidato_destino",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="flujos_destino",
                        to="elecciones.candidato",
                    ),
                ),
                (
                    "candidato_origen",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="flujos_origen",
                        to="elecciones.candidato",
                    ),
                ),
                (
                    "comuna",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="flujos",
                        to="comunas.comuna",
                    ),
                ),
            ],
            options={
                "verbose_name": "Flujo de transición",
                "verbose_name_plural": "Flujos de transición",
                "ordering": ["comuna", "candidato_origen", "-probabilidad_media"],
                "unique_together": {
                    ("comuna", "candidato_origen", "candidato_destino")
                },
            },
        ),
        migrations.CreateModel(
            name="ResultadoComuna",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("votos", models.IntegerField()),
                ("porcentaje", models.FloatField()),
                (
                    "candidato",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="resultados",
                        to="elecciones.candidato",
                    ),
                ),
                (
                    "comuna",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="resultados",
                        to="comunas.comuna",
                    ),
                ),
                (
                    "eleccion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="resultados",
                        to="elecciones.eleccion",
                    ),
                ),
            ],
            options={
                "verbose_name": "Resultado por comuna",
                "verbose_name_plural": "Resultados por comuna",
                "ordering": ["eleccion", "comuna", "-votos"],
                "unique_together": {("comuna", "eleccion", "candidato")},
            },
        ),
    ]
